# Generated by Django 5.1.7 on 2025-03-14 16:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='موبایل')),
                ('activation_code', models.CharField(blank=True, max_length=6, null=True)),
                ('gender', models.BooleanField(choices=[(True, 'مرد'), (False, 'زن')], verbose_name='جنسیت')),
                ('role', models.PositiveSmallIntegerField(choices=[(0, 'ورزشکار'), (1, 'مربی'), (2, 'اپراتور')], default=0, verbose_name='نوع کاربر')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('insurance', models.BooleanField(default=False, verbose_name='بیمه')),
                ('insurance_expiration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضای بیمه')),
                ('income_percentage', models.PositiveSmallIntegerField(default=0, verbose_name='درصد درآمد')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['date_joined'],
            },
        ),
        migrations.CreateModel(
            name='AthleteCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد شدن')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین آپدیت')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('payment_status', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('athlete', models.ForeignKey(limit_choices_to={'role': 0}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ورزشکار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آپدیت شده توسط')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام',
                'ordering': ['payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد شدن')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین آپدیت')),
                ('detail', models.TextField(max_length=1000, verbose_name='هزینه')),
                ('cost', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10000)], verbose_name='مبلغ به تومان')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آپدیت شده توسط')),
            ],
            options={
                'verbose_name': 'هزینه',
                'verbose_name_plural': 'هزینه\u200cها',
                'ordering': ['cost'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد شدن')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین آپدیت')),
                ('days', models.BooleanField(choices=[(True, 'روزهای زوج'), (False, 'روزهای فرد')], verbose_name='روزهای کلاس')),
                ('start_time', models.TimeField(verbose_name='زمان شروع کلاس')),
                ('end_time', models.TimeField(verbose_name='زمان پایان کلاس')),
                ('price', models.PositiveIntegerField(default=700000, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(99999999)], verbose_name='شهریه به تومان')),
                ('capacity', models.PositiveSmallIntegerField(default=40, verbose_name='ظرفیت کلاس')),
                ('coach', models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مربی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آپدیت شده توسط')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
                'ordering': ['sport'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد شدن')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین آپدیت')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('status', models.BooleanField(blank=True, verbose_name='حاضر')),
                ('athlete_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.athletecourse', verbose_name='ورزشکار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آپدیت شده توسط')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.course', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'حضور و غیاب',
                'verbose_name_plural': 'حضور و غیاب',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='athletecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.course', verbose_name='کلاس'),
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد شدن')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین آپدیت')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='نام سالن')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آپدیت شده توسط')),
            ],
            options={
                'verbose_name': 'سالن',
                'verbose_name_plural': 'سالن\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.hall', verbose_name='سالن'),
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد شدن')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین آپدیت')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='رشته')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آپدیت شده توسط')),
            ],
            options={
                'verbose_name': 'رشته',
                'verbose_name_plural': 'رشته\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.sport', verbose_name='رشته'),
        ),
    ]
